[config]
caching = true

[config.wallpaper]
set = true
pre_hook = "hyprpaper"
command = "hyprctl"
arguments = ["hyprpaper", "reload", ","]

[config.custom_colors]
"black" = "#000000"
"silver" = "#c0c0c0"
"gray" = "#808080"
"white" = "#ffffff"

"red" = "#ff0000"
"fuchsia" = "#ff00ff"
"blue" = "#0000ff"
"aqua" = "#00ffff"
"lime" = "#00ff00"
"yellow" = "#ffff00"

"brown" = "#800000"
"navy" = "#000080"
"green" = "#008000"

"deeppink" = "#ff0080"
"purple" = "#800080"
"blueviolet" = "#8000ff"
"dodgerblue" = "#0080ff"
"teal" = "#008080"
"springgreen" = "#00ff80"
"chartreuse" = "#80ff00"
"olive" = "#808000"
"orange" = "#ff8000"

"lightcoral" = "#ff8080"
"violet" = "#ff80ff"
"mediumslateblue" = "#8080ff"
"turquoise" = "#80ffff"
"palegreen" = "#80ff80"
"khaki" = "#ffff80"

# [templates.kitty]
# input_path = '~/.config/matugen/templates/kitty-colors.conf'
# output_path = '~/.config/kitty/colors-matugen.conf'
# post_hook = 'pkill -SIGUSR1 kitty'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar-extra]
input_path = '~/.config/matugen/templates/waybar-extra-colors.css'
output_path = '~/.config/waybar/themes/extra-colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/themes/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
input_path = '~/.config/matugen/templates/matugen-gtk.css'
# output_path = '~/.config/gtk-3.0/colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
# input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
# output_path = '~/.config/gtk-4.0/gtk.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.wleave]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wleave/colors.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.walker]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/walker/colors.css'

[templates.nwgdock]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.sequences]
input_path = '~/.config/matugen/templates/sequences'
output_path = '~/.cache/wal/sequences'

[templates.primary]
input_path = '~/.config/matugen/templates/primary'
output_path = '~/.config/ml4w/colors/primary'

[templates.secondary]
input_path = '~/.config/matugen/templates/secondary'
output_path = '~/.config/ml4w/colors/secondary'

[templates.on_surface]
input_path = '~/.config/matugen/templates/onsurface'
output_path = '~/.config/ml4w/colors/onsurface'

[templates.ohmyposh]
input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
output_path = '~/.config/ohmyposh/colors.json'
post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim.lua'
output_path = '~/.config/nvim/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

