[colors.primary]
background = '#0e1513'
foreground = '#dde4e1'
 
[colors.cursor]
text = '#dde4e1'
cursor = '#bec9c6' 
 
[colors.vi_mode_cursor]
text = '#0e1513'
cursor = '#82d5c9' 
 
[colors.search.matches]
foreground = '#3f4947' 
background = '#adcae6' 
 
[colors.search.focused_match]
foreground = '#3f4947' 
background = '#82d5c9' 
 
[colors.footer_bar]
foreground = '#3f4947' 
background = '#dde4e1' 
 
[colors.hints.start]
foreground = '#3f4947' 
background = '#b1ccc7' 
 
[colors.hints.end]
foreground = '#3f4947' 
background = '#b1ccc7' 
 
[colors.selection]
text = '#0e1513'
background = '#82d5c9'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#82d5c9' 
yellow = '#006a61' 
blue = '#82d5c9' 
magenta = '#adcae6' 
cyan = '#b1ccc7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
